import { 
  CustomModuleConfig, 
  CustomFeatureConfig, 
  FeatureFlagConfig, 
  NavigationConfigItem, 
  CustomFieldDefinition, 
  CustomFormConfig, 
  CustomTableViewConfig, 
  DashboardWidgetConfig, 
  ThemeConfig, 
  TemplateConfig, 
  WorkflowConfig, 
  NumberingConfig, 
  SchoolBrandingConfig, 
  LocalizationConfig, 
  UserPreferencesConfig, 
  ConfigVersionSnapshot 
} from '../types';

export const initialCustomModules: CustomModuleConfig[] = [
  {
    id: 'mod-dashboard',
    name: 'dashboard',
    displayName: 'Executive Dashboard',
    description: 'Real-time administrative metrics, alerts, KPI cards, and enrollment analytics.',
    icon: 'LayoutDashboard',
    category: 'Core',
    type: 'BUILTIN',
    route: 'dashboard',
    sortOrder: 1,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'VICE_PRINCIPAL', 'TEACHER', 'ACCOUNTANT'],
    schoolScope: 'ALL',
    version: '2.4.0',
    updatedAt: '2025-04-28 10:00 AM',
    featuresCount: 8,
    badgeColor: '#2563eb',
    isDeletable: false,
  },
  {
    id: 'mod-students',
    name: 'students',
    displayName: 'Student Information System',
    description: 'Comprehensive student directory, KYC profiles, parent records, and ID issuance.',
    icon: 'Users',
    category: 'Student Services',
    type: 'BUILTIN',
    route: 'students',
    sortOrder: 2,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER', 'RECEPTIONIST'],
    schoolScope: 'ALL',
    version: '3.1.2',
    updatedAt: '2025-04-28 09:30 AM',
    featuresCount: 12,
    badgeColor: '#3b82f6',
    isDeletable: false,
  },
  {
    id: 'mod-attendance',
    name: 'attendance',
    displayName: 'Attendance & Biometrics',
    description: 'Daily class attendance registers, RFID/biometric device sync, and statutory alerts.',
    icon: 'CalendarCheck',
    category: 'Academic',
    type: 'CONFIGURABLE',
    route: 'attendance',
    sortOrder: 3,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'],
    schoolScope: 'ALL',
    version: '2.8.0',
    updatedAt: '2025-04-28 09:15 AM',
    featuresCount: 9,
    badgeColor: '#10b981',
    isDeletable: false,
  },
  {
    id: 'mod-fees',
    name: 'fees',
    displayName: 'Fees & Accounting',
    description: 'Fee schedules, automated challan generation, online gateway collections, and receipts.',
    icon: 'Banknote',
    category: 'Finance',
    type: 'CONFIGURABLE',
    route: 'fees',
    sortOrder: 4,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT', 'PRINCIPAL'],
    schoolScope: 'ALL',
    version: '3.0.1',
    updatedAt: '2025-04-27 04:00 PM',
    featuresCount: 14,
    badgeColor: '#f59e0b',
    isDeletable: false,
  },
  {
    id: 'mod-examinations',
    name: 'examinations',
    displayName: 'Examinations & Report Cards',
    description: 'Term exam scheduling, hall ticket generation, gradebook entry, and CBSE-format reports.',
    icon: 'Award',
    category: 'Academic',
    type: 'CONFIGURABLE',
    route: 'examinations',
    sortOrder: 5,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'],
    schoolScope: 'ALL',
    version: '2.5.0',
    updatedAt: '2025-04-26 11:20 AM',
    featuresCount: 10,
    badgeColor: '#8b5cf6',
    isDeletable: false,
  },
  {
    id: 'mod-staff',
    name: 'staff',
    displayName: 'Staff & HR Payroll',
    description: 'Faculty management, biometric punch logs, leave approvals, and automated payslips.',
    icon: 'UserCheck',
    category: 'Administration',
    type: 'CONFIGURABLE',
    route: 'staff',
    sortOrder: 6,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'HR_MANAGER', 'PRINCIPAL'],
    schoolScope: 'ALL',
    version: '2.2.0',
    updatedAt: '2025-04-25 03:30 PM',
    featuresCount: 8,
    badgeColor: '#059669',
    isDeletable: false,
  },
  {
    id: 'mod-admissions',
    name: 'admissions',
    displayName: 'New Admissions CRM',
    description: 'Lead tracking, online enquiry forms, document verification, and seat allocation.',
    icon: 'UserPlus',
    category: 'Student Services',
    type: 'CONFIGURABLE',
    route: 'admissions',
    sortOrder: 7,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST', 'PRINCIPAL'],
    schoolScope: 'ALL',
    version: '2.1.0',
    updatedAt: '2025-04-24 02:10 PM',
    featuresCount: 7,
    badgeColor: '#0284c7',
    isDeletable: false,
  },
  {
    id: 'mod-academics',
    name: 'academics',
    displayName: 'Academics & Lesson Plans',
    description: 'Syllabus tracker, digital lesson plan repositories, homework dispatch, and question banks.',
    icon: 'BookOpenCheck',
    category: 'Academic',
    type: 'CONFIGURABLE',
    route: 'academics',
    sortOrder: 8,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'],
    schoolScope: 'ALL',
    version: '1.9.0',
    updatedAt: '2025-04-23 05:40 PM',
    featuresCount: 6,
    badgeColor: '#6366f1',
    isDeletable: false,
  },
  {
    id: 'mod-welfare',
    name: 'welfare',
    displayName: 'Student Welfare & Health',
    description: 'Disciplinary logs, medical health checkups, statutory certificates, and alumni network.',
    icon: 'HeartHandshake',
    category: 'Student Services',
    type: 'CUSTOM_DATA',
    route: 'welfare',
    sortOrder: 9,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'],
    schoolScope: 'ALL',
    version: '1.5.0',
    updatedAt: '2025-04-22 01:00 PM',
    featuresCount: 6,
    badgeColor: '#ec4899',
    isDeletable: true,
  },
  {
    id: 'mod-inventory',
    name: 'inventory',
    displayName: 'Inventory & Fixed Assets',
    description: 'Consumable stock items, vendor purchasing, classroom fixed asset tracking, and depreciation.',
    icon: 'Boxes',
    category: 'Administration',
    type: 'CUSTOM_DATA',
    route: 'inventory',
    sortOrder: 10,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT'],
    schoolScope: 'ALL',
    version: '1.4.0',
    updatedAt: '2025-04-21 11:30 AM',
    featuresCount: 5,
    badgeColor: '#ea580c',
    isDeletable: true,
  },
  {
    id: 'mod-integrations',
    name: 'integrations',
    displayName: 'Gateways & Hardware Hub',
    description: 'Biometric terminals, SMS gateways, WhatsApp Business API, GPS vehicle tracking, and Tally.',
    icon: 'Cpu',
    category: 'Integrations',
    type: 'INTEGRATION',
    route: 'integrations',
    sortOrder: 11,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN'],
    schoolScope: 'ALL',
    version: '2.0.0',
    updatedAt: '2025-04-20 04:15 PM',
    featuresCount: 6,
    badgeColor: '#475569',
    isDeletable: false,
  },
  {
    id: 'mod-reports',
    name: 'reports',
    displayName: 'Reports & Compliance Audits',
    description: 'Statutory compliance exports, fee collection ledgers, attendance summaries, and CSV/PDF reports.',
    icon: 'BarChart3',
    category: 'Administration',
    type: 'BUILTIN',
    route: 'reports',
    sortOrder: 12,
    status: 'ENABLED',
    requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'ACCOUNTANT'],
    schoolScope: 'ALL',
    version: '2.6.0',
    updatedAt: '2025-04-19 10:00 AM',
    featuresCount: 11,
    badgeColor: '#7c3aed',
    isDeletable: false,
  }
];

export const initialCustomFeatures: CustomFeatureConfig[] = [
  { id: 'feat-att-biometric', moduleId: 'mod-attendance', name: 'Biometric Terminal Sync', description: 'Automated facial & thumb scanner pull via TCP/IP listener', enabled: true, requiredRole: ['SUPER_ADMIN', 'ADMIN'], dependencies: ['mod-integrations'], scope: 'SYSTEM' },
  { id: 'feat-att-sms', moduleId: 'mod-attendance', name: 'Automated Parent Absence SMS', description: 'Trigger immediate SMS when student is marked absent in period 1', enabled: true, requiredRole: ['SUPER_ADMIN', 'ADMIN', 'TEACHER'], dependencies: ['mod-integrations'], scope: 'SCHOOL' },
  { id: 'feat-fee-online', moduleId: 'mod-fees', name: 'UPI & Payment Gateway Checkout', description: 'Accept online fee payments with instant automated receipt generation', enabled: true, requiredRole: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT'], dependencies: ['mod-integrations'], scope: 'SYSTEM' },
  { id: 'feat-fee-concession', moduleId: 'mod-fees', name: 'Staff Child & Merit Fee Concessions', description: 'Configurable percentage fee waivers with multi-tier approvals', enabled: true, requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL'], dependencies: [], scope: 'SCHOOL' },
  { id: 'feat-exam-cbe', moduleId: 'mod-examinations', name: 'CBSE / State Board Report Card Formats', description: 'Standardized 9-point scholastic & co-scholastic grading schemas', enabled: true, requiredRole: ['SUPER_ADMIN', 'ADMIN', 'TEACHER'], dependencies: [], scope: 'SCHOOL' },
  { id: 'feat-stu-idgen', moduleId: 'mod-students', name: 'Barcode ID Card Batch Generation', description: 'Generate high-resolution printable ID cards with QR verification', enabled: true, requiredRole: ['SUPER_ADMIN', 'ADMIN'], dependencies: [], scope: 'SCHOOL' },
  { id: 'feat-transport-gps', moduleId: 'mod-integrations', name: 'Live Bus Route GPS Tracking', description: 'Real-time vehicle speed and geo-fence alerts for school buses', enabled: true, requiredRole: ['SUPER_ADMIN', 'TRANSPORT_MANAGER'], dependencies: ['mod-integrations'], scope: 'CAMPUS' },
  { id: 'feat-ai-lesson', moduleId: 'mod-academics', name: 'AI Lesson Plan Draft Generation', description: 'Generate NEP-compliant lesson plans and bloom taxonomy objectives', enabled: true, requiredRole: ['SUPER_ADMIN', 'ADMIN', 'TEACHER'], dependencies: [], isBeta: true, scope: 'SYSTEM' }
];

export const initialFeatureFlags: FeatureFlagConfig[] = [
  { key: 'AI_LESSON_PLANNER', label: 'AI Lesson Plan & Quiz Generator', description: 'Enables Gemini-powered smart lesson blueprinting and rubric drafting.', enabled: true, category: 'AI & Automation', scope: 'GLOBAL', updatedAt: '2025-04-28' },
  { key: 'BIOMETRIC_AUTO_PUNCH', label: 'Real-Time Biometric Punch Listener', description: 'Listens for hardware device event payloads from school LAN turns.', enabled: true, category: 'Hardware', scope: 'SCHOOL', updatedAt: '2025-04-28' },
  { key: 'WHATSAPP_TRANSACTIONAL_ALERTS', label: 'WhatsApp Instant Notifications', description: 'Dispatches fees receipts and exam hall tickets via verified WhatsApp business API.', enabled: true, category: 'General', scope: 'SCHOOL', updatedAt: '2025-04-27' },
  { key: 'TWO_FACTOR_ADMIN_AUTH', label: 'Enforce 2FA for Super Admin Roles', description: 'Requires TOTP Authenticator code on privileged system logins.', enabled: false, category: 'Security', scope: 'GLOBAL', updatedAt: '2025-04-25' },
  { key: 'DIGITAL_FEE_INSTALLMENTS', label: 'Multi-Part Split Fee Installments', description: 'Allows parents to divide annual tuition fees into 3 equal tranches.', enabled: true, category: 'General', scope: 'SCHOOL', updatedAt: '2025-04-26' },
  { key: 'OFFLINE_FIRST_CACHE', label: 'Aggressive Client SQLite Sync Cache', description: 'Persists active session records for low-latency offline resilience.', enabled: true, category: 'Experimental', scope: 'GLOBAL', updatedAt: '2025-04-28' },
];

export const initialNavigationItems: NavigationConfigItem[] = [
  { id: 'nav-1', moduleId: 'mod-dashboard', label: 'Dashboard', customLabel: 'Dashboard', group: 'Overview', icon: 'LayoutDashboard', order: 1, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'VICE_PRINCIPAL', 'TEACHER', 'ACCOUNTANT'], shortcut: 'Ctrl+1', isPinned: true },
  { id: 'nav-2', moduleId: 'mod-frontoffice', label: 'Front Office & CRM', customLabel: 'Front Office & CRM', group: 'Administration', icon: 'Headphones', order: 2, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST', 'PRINCIPAL'], isPinned: false },
  { id: 'nav-3', moduleId: 'mod-students', label: 'Students', customLabel: 'Students', group: 'Student Services', icon: 'Users', order: 3, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER', 'RECEPTIONIST'], shortcut: 'Ctrl+2', isPinned: true },
  { id: 'nav-4', moduleId: 'mod-admissions', label: 'Admissions', customLabel: 'Admissions', group: 'Student Services', icon: 'UserPlus', order: 4, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST', 'PRINCIPAL'], shortcut: 'Ctrl+7', isPinned: false },
  { id: 'nav-5', moduleId: 'mod-academics', label: 'Academics & Lessons', customLabel: 'Academics & Lessons', group: 'Academics', icon: 'BookOpenCheck', order: 5, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'], shortcut: 'Ctrl+8', isPinned: false },
  { id: 'nav-6', moduleId: 'mod-classes', label: 'Classes & Sections', customLabel: 'Classes & Sections', group: 'Academics', icon: 'GraduationCap', order: 6, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'], isPinned: false },
  { id: 'nav-7', moduleId: 'mod-attendance', label: 'Attendance', customLabel: 'Attendance', group: 'Academics', icon: 'CalendarCheck', order: 7, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'], shortcut: 'Ctrl+3', isPinned: true },
  { id: 'nav-8', moduleId: 'mod-timetable', label: 'Timetable', customLabel: 'Timetable', group: 'Academics', icon: 'CalendarDays', order: 8, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'], isPinned: false },
  { id: 'nav-9', moduleId: 'mod-examinations', label: 'Examinations', customLabel: 'Examinations', group: 'Academics', icon: 'Award', order: 9, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'], shortcut: 'Ctrl+5', isPinned: false },
  { id: 'nav-10', moduleId: 'mod-fees', label: 'Fees & Accounting', customLabel: 'Fees & Accounting', group: 'Finance', icon: 'Banknote', order: 10, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT', 'PRINCIPAL'], shortcut: 'Ctrl+4', isPinned: true },
  { id: 'nav-11', moduleId: 'mod-staff', label: 'Staff & Payroll', customLabel: 'Staff & Payroll', group: 'Administration', icon: 'UserCheck', order: 11, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'HR_MANAGER', 'PRINCIPAL'], shortcut: 'Ctrl+6', isPinned: false },
  { id: 'nav-12', moduleId: 'mod-welfare', label: 'Student Welfare & Health', customLabel: 'Student Welfare & Health', group: 'Student Services', icon: 'HeartHandshake', order: 12, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'], isPinned: false },
  { id: 'nav-13', moduleId: 'mod-inventory', label: 'Inventory & Assets', customLabel: 'Inventory & Assets', group: 'Administration', icon: 'Boxes', order: 13, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT'], isPinned: false },
  { id: 'nav-14', moduleId: 'mod-library', label: 'Library', customLabel: 'Library', group: 'Academic', icon: 'BookOpen', order: 14, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'LIBRARIAN', 'TEACHER'], isPinned: false },
  { id: 'nav-15', moduleId: 'mod-transport', label: 'Transport Fleet', customLabel: 'Transport Fleet', group: 'Logistics', icon: 'Bus', order: 15, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'TRANSPORT_MANAGER'], isPinned: false },
  { id: 'nav-16', moduleId: 'mod-hostel', label: 'Hostel Rooms', customLabel: 'Hostel Rooms', group: 'Logistics', icon: 'Building2', order: 16, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'HOSTEL_WARDEN'], isPinned: false },
  { id: 'nav-17', moduleId: 'mod-integrations', label: 'Gateways & Hardware', customLabel: 'Gateways & Hardware', group: 'System', icon: 'Cpu', order: 17, visible: true, roles: ['SUPER_ADMIN', 'ADMIN'], isPinned: false },
  { id: 'nav-18', moduleId: 'mod-reports', label: 'Reports & Audits', customLabel: 'Reports & Audits', group: 'System', icon: 'BarChart3', order: 18, visible: true, roles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'ACCOUNTANT'], shortcut: 'Ctrl+9', isPinned: false },
  { id: 'nav-19', moduleId: 'mod-customization', label: 'Customization Center', customLabel: 'Customization & Studio', group: 'System', icon: 'Sliders', order: 19, visible: true, roles: ['SUPER_ADMIN', 'ADMIN'], isPinned: true },
  { id: 'nav-20', moduleId: 'mod-settings', label: 'Settings', customLabel: 'Settings', group: 'System', icon: 'Settings', order: 20, visible: true, roles: ['SUPER_ADMIN', 'ADMIN'], shortcut: 'Ctrl+0', isPinned: false },
];

export const initialCustomFields: CustomFieldDefinition[] = [
  { id: 'cf-1', entityType: 'STUDENT', fieldName: 'Aadhaar / National ID', fieldKey: 'aadhaarNumber', fieldType: 'TEXT', placeholder: '12-digit UIDAI format', isRequired: false, isUnique: true, isSearchable: true, isFilterable: false, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'RECEPTIONIST'], section: 'Identity & Legal', order: 1, validationRegex: '^[0-9]{12}$' },
  { id: 'cf-2', entityType: 'STUDENT', fieldName: 'Second Language Option', fieldKey: 'secondLanguage', fieldType: 'SELECT', defaultValue: 'Hindi', isRequired: true, isUnique: false, isSearchable: true, isFilterable: true, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'TEACHER'], options: ['Hindi', 'Sanskrit', 'French', 'German', 'Spanish', 'Tamil', 'Telugu'], section: 'Academics', order: 2 },
  { id: 'cf-3', entityType: 'STUDENT', fieldName: 'Dietary Preference', fieldKey: 'dietaryPreference', fieldType: 'SELECT', defaultValue: 'Vegetarian', isRequired: false, isUnique: false, isSearchable: false, isFilterable: true, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'HOSTEL_WARDEN', 'TEACHER'], options: ['Vegetarian', 'Non-Vegetarian', 'Jain Vegan', 'Eggitarian'], section: 'Health & Lifestyle', order: 3 },
  { id: 'cf-4', entityType: 'STUDENT', fieldName: 'RTE (Right to Education) Quota', fieldKey: 'isRteQuota', fieldType: 'BOOLEAN', defaultValue: false, isRequired: false, isUnique: false, isSearchable: false, isFilterable: true, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT'], section: 'Government Schemes', order: 4 },
  { id: 'cf-5', entityType: 'STAFF', fieldName: 'PF / UAN Number', fieldKey: 'uanNumber', fieldType: 'TEXT', placeholder: '12-digit EPF UAN', isRequired: false, isUnique: true, isSearchable: true, isFilterable: false, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'HR_MANAGER'], section: 'Payroll & Statutory', order: 1 },
  { id: 'cf-6', entityType: 'STAFF', fieldName: 'Emergency Blood Group', fieldKey: 'bloodGroup', fieldType: 'SELECT', isRequired: true, isUnique: false, isSearchable: false, isFilterable: true, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'HR_MANAGER', 'TEACHER'], options: ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'], section: 'Personal Details', order: 2 },
  { id: 'cf-7', entityType: 'ADMISSION', fieldName: 'Sibling Concession Applied', fieldKey: 'hasSiblingEnrolled', fieldType: 'BOOLEAN', defaultValue: false, isRequired: false, isUnique: false, isSearchable: false, isFilterable: true, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST'], section: 'Fee Structure', order: 1 },
  { id: 'cf-8', entityType: 'FEE', fieldName: 'Bank Transaction Ref / UTR', fieldKey: 'utrReference', fieldType: 'TEXT', placeholder: 'e.g. UPI-RR-98124801', isRequired: false, isUnique: false, isSearchable: true, isFilterable: false, visibleToRoles: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT'], section: 'Payment Audit', order: 1 }
];

export const initialCustomForms: CustomFormConfig[] = [
  {
    id: 'form-adm-std',
    name: 'Standard Student Admission Form 2025',
    entityType: 'ADMISSION',
    description: 'Multi-section registration form with conditional transport and hostel questionnaires.',
    status: 'PUBLISHED',
    version: 3,
    updatedAt: '2025-04-28 09:00 AM',
    updatedBy: 'Super Admin',
    sections: [
      {
        id: 'sec-1',
        title: 'Applicant Basic Profile',
        description: 'Primary demographic information and student identity',
        columns: 2,
        fieldKeys: ['studentName', 'gender', 'dob', 'appliedClass', 'bloodGroup']
      },
      {
        id: 'sec-2',
        title: 'Parent & Guardian Contact',
        description: 'Primary contact for SMS alerts and fee challans',
        columns: 2,
        fieldKeys: ['parentName', 'phone', 'email', 'address']
      },
      {
        id: 'sec-3',
        title: 'Transport Logistics',
        description: 'Bus route selection if student requires school commute',
        columns: 2,
        fieldKeys: ['transportRouteId', 'pickupStop'],
        conditionalRule: {
          triggerFieldKey: 'transportRequired',
          operator: 'EQUALS',
          value: 'true'
        }
      }
    ]
  }
];

export const initialTableViews: CustomTableViewConfig[] = [
  {
    id: 'view-stu-default',
    entityType: 'STUDENT',
    name: 'Standard Comprehensive View',
    isDefault: true,
    density: 'COMFORTABLE',
    visibleColumns: ['admissionNo', 'studentName', 'className', 'section', 'parentName', 'parentPhone', 'feeStatus', 'attendancePercent', 'status'],
    columnOrder: ['admissionNo', 'studentName', 'className', 'section', 'parentName', 'parentPhone', 'feeStatus', 'attendancePercent', 'status'],
    pinnedColumns: ['admissionNo', 'studentName'],
    sortBy: 'admissionNo',
    sortDirection: 'asc',
    scope: 'SYSTEM'
  },
  {
    id: 'view-stu-feepending',
    entityType: 'STUDENT',
    name: 'Fee Defaulters & Outstanding Balances',
    isDefault: false,
    density: 'COMPACT',
    visibleColumns: ['admissionNo', 'studentName', 'className', 'parentPhone', 'feeStatus', 'pendingAmount'],
    columnOrder: ['admissionNo', 'studentName', 'className', 'parentPhone', 'feeStatus', 'pendingAmount'],
    pinnedColumns: ['admissionNo', 'studentName'],
    sortBy: 'pendingAmount',
    sortDirection: 'desc',
    scope: 'SYSTEM'
  }
];

export const initialDashboardWidgets: DashboardWidgetConfig[] = [
  { id: 'w-kpi-students', title: 'Total Student Strength', type: 'KPI', gridSpan: 3, enabled: true, order: 1, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL'] },
  { id: 'w-kpi-staff', title: 'Active Faculty Strength', type: 'KPI', gridSpan: 3, enabled: true, order: 2, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'HR_MANAGER'] },
  { id: 'w-kpi-fees', title: 'Pending Tuition Balance', type: 'FEES_SUMMARY', gridSpan: 3, enabled: true, order: 3, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT'] },
  { id: 'w-kpi-att', title: 'Today Campus Attendance', type: 'ATTENDANCE_GAUGE', gridSpan: 3, enabled: true, order: 4, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER'] },
  { id: 'w-chart-enrollment', title: 'Monthly Admissions Trend', type: 'CHART', gridSpan: 6, enabled: true, order: 5, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL'] },
  { id: 'w-feed-activities', title: 'Live Activity Stream', type: 'RECENT_ACTIVITY', gridSpan: 6, enabled: true, order: 6, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER', 'ACCOUNTANT'] },
  { id: 'w-quick-actions', title: 'Administrative Quick Actions', type: 'QUICK_ACTIONS', gridSpan: 6, enabled: true, order: 7, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'ACCOUNTANT', 'RECEPTIONIST'] },
  { id: 'w-ai-insights', title: 'AI Retention & Risk Insights', type: 'AI_INSIGHTS', gridSpan: 6, enabled: true, order: 8, targetRoles: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL'] }
];

export const initialThemePresets: ThemeConfig[] = [
  {
    id: 'theme-professional-blue',
    name: 'Professional Blue (Default Enterprise)',
    isDefault: true,
    mode: 'LIGHT',
    primaryColor: '#2563eb',
    secondaryColor: '#1e293b',
    accentColor: '#10b981',
    sidebarBg: '#121c2d',
    sidebarTextColor: '#e2e8f0',
    fontFamily: 'Plus Jakarta Sans',
    borderRadius: 'medium',
    density: 'comfortable',
    version: 1,
    status: 'PUBLISHED'
  },
  {
    id: 'theme-modern-emerald',
    name: 'Modern Emerald Campus',
    isDefault: false,
    mode: 'LIGHT',
    primaryColor: '#059669',
    secondaryColor: '#0f172a',
    accentColor: '#3b82f6',
    sidebarBg: '#064e3b',
    sidebarTextColor: '#ecfdf5',
    fontFamily: 'Inter',
    borderRadius: 'large',
    density: 'comfortable',
    version: 1,
    status: 'PUBLISHED'
  },
  {
    id: 'theme-dark-obsidian',
    name: 'Dark Obsidian Workstation',
    isDefault: false,
    mode: 'DARK',
    primaryColor: '#3b82f6',
    secondaryColor: '#0f172a',
    accentColor: '#6366f1',
    sidebarBg: '#090d16',
    sidebarTextColor: '#f8fafc',
    fontFamily: 'JetBrains Mono',
    borderRadius: 'small',
    density: 'compact',
    version: 1,
    status: 'PUBLISHED'
  },
  {
    id: 'theme-high-contrast',
    name: 'High Contrast Accessibility (WCAG AAA)',
    isDefault: false,
    mode: 'LIGHT',
    primaryColor: '#000000',
    secondaryColor: '#111827',
    accentColor: '#0044cc',
    sidebarBg: '#000000',
    sidebarTextColor: '#ffffff',
    fontFamily: 'Segoe UI',
    borderRadius: 'none',
    density: 'spacious',
    version: 1,
    status: 'PUBLISHED'
  }
];

export const initialTemplates: TemplateConfig[] = [
  {
    id: 'tmpl-cert-bonafide',
    name: 'Standard Bonafide Student Certificate',
    category: 'CERTIFICATE',
    version: 2,
    status: 'PUBLISHED',
    layout: 'PORTRAIT',
    headerText: 'OFFICE OF THE PRINCIPAL',
    footerText: 'This certificate is valid for official submission to passport, visa, and scholarship authorities.',
    contentBody: `This is to certify that {{student.name}}, son/daughter of {{parent.name}}, residing at {{student.address}}, is a bonafide student of Delhi Public International School, studying in Class {{student.class}} (Section {{student.section}}) under Admission No. {{student.admission_no}} during the academic year {{academic_year.name}}.\n\nAccording to school official records, their date of birth is {{student.dob}}. Their character and conduct during their study here have been exemplary.`,
    variables: ['{{student.name}}', '{{parent.name}}', '{{student.address}}', '{{student.class}}', '{{student.section}}', '{{student.admission_no}}', '{{academic_year.name}}', '{{student.dob}}', '{{certificate.number}}', '{{date}}'],
    signatureRequired: true,
    qrVerificationEnabled: true,
    schoolBranding: true,
    updatedAt: '2025-04-28',
    updatedBy: 'Principal'
  },
  {
    id: 'tmpl-id-student',
    name: 'Standard Student Smart ID Card (Front & Back)',
    category: 'ID_CARD',
    version: 3,
    status: 'PUBLISHED',
    layout: 'PORTRAIT',
    headerText: 'STUDENT IDENTITY CARD',
    footerText: 'If found, please return to Delhi Public International School, Institutional Area, New Delhi.',
    contentBody: `STUDENT: {{student.name}}\nADM NO: {{student.admission_no}}\nCLASS: {{student.class}} - {{student.section}}\nBLOOD GROUP: {{student.blood_group}}\nEMERGENCY PHONE: {{parent.phone}}`,
    variables: ['{{student.name}}', '{{student.admission_no}}', '{{student.class}}', '{{student.section}}', '{{student.blood_group}}', '{{parent.phone}}', '{{school.address}}'],
    signatureRequired: true,
    qrVerificationEnabled: true,
    schoolBranding: true,
    updatedAt: '2025-04-27',
    updatedBy: 'Admin'
  },
  {
    id: 'tmpl-fee-receipt',
    name: 'Official Cashier Fee Payment Receipt',
    category: 'RECEIPT',
    version: 4,
    status: 'PUBLISHED',
    layout: 'STANDARD',
    headerText: 'FEE PAYMENT RECEIPT (STUDENT COPY)',
    footerText: 'Fees once paid are non-refundable. Please retain this receipt for annual tax deductions under Sec 80C.',
    contentBody: `Received with thanks from {{parent.name}} on behalf of student {{student.name}} (Admission No. {{student.admission_no}}, Class {{student.class}}-{{student.section}}) the sum of {{payment.amount}} towards {{fee.invoice_title}} via {{payment.method}}.\n\nReceipt Reference: {{payment.receipt_no}}\nBalance Pending: {{invoice.balance}}`,
    variables: ['{{parent.name}}', '{{student.name}}', '{{student.admission_no}}', '{{student.class}}', '{{student.section}}', '{{payment.amount}}', '{{fee.invoice_title}}', '{{payment.method}}', '{{payment.receipt_no}}', '{{invoice.balance}}', '{{date}}'],
    signatureRequired: true,
    qrVerificationEnabled: true,
    schoolBranding: true,
    updatedAt: '2025-04-28',
    updatedBy: 'Accountant'
  },
  {
    id: 'tmpl-sms-attendance',
    name: 'Daily Absence SMS Alert (Guardian)',
    category: 'SMS',
    version: 1,
    status: 'PUBLISHED',
    layout: 'STANDARD',
    contentBody: `Dear Parent, your ward {{student.name}} (Class {{student.class}}-{{student.section}}) is marked ABSENT today ({{date}}) at {{school.name}}. If this is an authorized leave, please submit via the student portal or call {{school.phone}}.`,
    variables: ['{{student.name}}', '{{student.class}}', '{{student.section}}', '{{date}}', '{{school.name}}', '{{school.phone}}'],
    signatureRequired: false,
    qrVerificationEnabled: false,
    schoolBranding: false,
    updatedAt: '2025-04-28',
    updatedBy: 'System'
  },
  {
    id: 'tmpl-whatsapp-fee-notice',
    name: 'WhatsApp Outstanding Fee Reminder',
    category: 'WHATSAPP',
    version: 2,
    status: 'PUBLISHED',
    layout: 'STANDARD',
    contentBody: `Namaste {{parent.name}},\n\nThis is a gentle reminder that tuition fee challan for {{student.name}} (Class {{student.class}}) has a pending balance of *{{invoice.balance}}* due by *{{invoice.due_date}}*.\n\nYou can complete instant zero-fee UPI payment via link: {{payment.link}}\n\nRegards,\n*{{school.name}} Accounts Office*`,
    variables: ['{{parent.name}}', '{{student.name}}', '{{student.class}}', '{{invoice.balance}}', '{{invoice.due_date}}', '{{payment.link}}', '{{school.name}}'],
    signatureRequired: false,
    qrVerificationEnabled: false,
    schoolBranding: true,
    updatedAt: '2025-04-28',
    updatedBy: 'Accountant'
  }
];

export const initialWorkflows: WorkflowConfig[] = [
  {
    id: 'wf-admissions',
    name: 'Student Admission Lifecycle Workflow',
    module: 'ADMISSIONS',
    description: 'Multi-stage admission approval pipeline from enquiry to certified classroom enrollment.',
    status: 'ACTIVE',
    slaHours: 48,
    states: [
      { id: 'ENQUIRY', name: 'Enquiry Received', color: '#64748b', isFinal: false },
      { id: 'APPLICATION', name: 'Application Submitted', color: '#0284c7', isFinal: false },
      { id: 'VERIFICATION', name: 'Documents Verified', color: '#f59e0b', isFinal: false },
      { id: 'APPROVED', name: 'Principal Approved', color: '#8b5cf6', isFinal: false },
      { id: 'ENROLLED', name: 'Student Enrolled', color: '#10b981', isFinal: true },
      { id: 'REJECTED', name: 'Application Rejected', color: '#ef4444', isFinal: true },
    ],
    transitions: [
      { fromState: 'ENQUIRY', toState: 'APPLICATION', actionLabel: 'Convert to Application', requiredRole: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST'], notifyApplicant: true, notifyParent: true },
      { fromState: 'APPLICATION', toState: 'VERIFICATION', actionLabel: 'Verify Certificates', requiredRole: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST'], notifyApplicant: false, notifyParent: false },
      { fromState: 'VERIFICATION', toState: 'APPROVED', actionLabel: 'Principal Approval', requiredRole: ['SUPER_ADMIN', 'PRINCIPAL'], notifyApplicant: true, notifyParent: true },
      { fromState: 'APPROVED', toState: 'ENROLLED', actionLabel: 'Enroll & Generate ID', requiredRole: ['SUPER_ADMIN', 'ADMIN', 'ACCOUNTANT'], notifyApplicant: true, notifyParent: true },
      { fromState: 'APPLICATION', toState: 'REJECTED', actionLabel: 'Reject Application', requiredRole: ['SUPER_ADMIN', 'PRINCIPAL'], notifyApplicant: true, notifyParent: true },
      { fromState: 'VERIFICATION', toState: 'REJECTED', actionLabel: 'Reject Invalid Docs', requiredRole: ['SUPER_ADMIN', 'ADMIN', 'PRINCIPAL'], notifyApplicant: true, notifyParent: true }
    ]
  },
  {
    id: 'wf-staff-leaves',
    name: 'Staff Leave Approval Matrix',
    module: 'LEAVE',
    description: 'Faculty leave applications routed through department heads and principal sign-off.',
    status: 'ACTIVE',
    slaHours: 24,
    states: [
      { id: 'APPLIED', name: 'Pending Review', color: '#f59e0b', isFinal: false },
      { id: 'APPROVED', name: 'Leave Approved', color: '#10b981', isFinal: true },
      { id: 'REJECTED', name: 'Leave Declined', color: '#ef4444', isFinal: true }
    ],
    transitions: [
      { fromState: 'APPLIED', toState: 'APPROVED', actionLabel: 'Approve Leave Request', requiredRole: ['SUPER_ADMIN', 'PRINCIPAL', 'HR_MANAGER'], notifyApplicant: true, notifyParent: false },
      { fromState: 'APPLIED', toState: 'REJECTED', actionLabel: 'Decline Request', requiredRole: ['SUPER_ADMIN', 'PRINCIPAL', 'HR_MANAGER'], notifyApplicant: true, notifyParent: false }
    ]
  }
];

export const initialNumberingConfigs: NumberingConfig[] = [
  { id: 'num-stu', entity: 'STUDENT', name: 'Student Permanent Admission No', prefix: 'ADM', suffix: '', includeYear: true, includeCampus: false, padding: 4, currentSequence: 1048, resetFrequency: 'NEVER' },
  { id: 'num-adm', entity: 'ADMISSION', name: 'Online Application Tracking Number', prefix: 'APP', suffix: '', includeYear: true, includeCampus: false, padding: 5, currentSequence: 5240, resetFrequency: 'YEARLY' },
  { id: 'num-inv', entity: 'INVOICE', name: 'Fee Challan Invoice Number', prefix: 'INV', suffix: '', includeYear: true, includeCampus: true, padding: 5, currentSequence: 10420, resetFrequency: 'ACADEMIC_YEAR' },
  { id: 'num-rcp', entity: 'RECEIPT', name: 'Payment Transaction Receipt Number', prefix: 'RCP', suffix: '', includeYear: true, includeCampus: false, padding: 6, currentSequence: 50482, resetFrequency: 'ACADEMIC_YEAR' },
  { id: 'num-cert', entity: 'CERTIFICATE', name: 'Official Institutional Certificate No', prefix: 'CERT', suffix: '', includeYear: true, includeCampus: false, padding: 4, currentSequence: 312, resetFrequency: 'YEARLY' },
  { id: 'num-stf', entity: 'STAFF', name: 'Staff Employee Identification Code', prefix: 'EMP', suffix: '', includeYear: false, includeCampus: false, padding: 3, currentSequence: 89, resetFrequency: 'NEVER' }
];

export const initialSchoolBranding: SchoolBrandingConfig = {
  schoolName: 'Delhi Public International School',
  shortName: 'DPIS New Delhi',
  tagline: 'Smart Education, Better Tomorrow',
  affiliationNo: 'CBSE-AFF/2025/98214',
  boardName: 'Central Board of Secondary Education (CBSE)',
  logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=120&h=120&fit=crop&crop=faces',
  primaryBrandColor: '#2563eb',
  secondaryBrandColor: '#1e293b',
  address: 'Sector 14, Institutional Area, South Extension',
  city: 'New Delhi',
  state: 'Delhi',
  pincode: '110001',
  phone: '+91 11 2894 7700',
  email: 'admin@schoolerp.edu.in',
  website: 'https://schoolerp.internal'
};

export const initialLocalization: LocalizationConfig = {
  language: 'en',
  dateFormat: 'DD/MM/YYYY',
  timeFormat: '12_HOUR',
  currency: 'INR (₹)',
  numberFormat: 'INDIAN_LAKHS',
  weekStartDay: 'MONDAY',
  academicYearStartMonth: 'APRIL'
};

export const initialUserPreferences: UserPreferencesConfig = {
  userId: 'usr-admin-1',
  themeId: 'theme-professional-blue',
  compactDensity: false,
  sidebarCollapsed: false,
  defaultLandingModule: 'dashboard',
  favoriteModules: ['dashboard', 'students', 'attendance', 'fees', 'customization'],
  enableKeyboardShortcuts: true,
  enableAudioNotifications: true,
  autoRefreshInterval: 300
};

export const initialVersionSnapshots: ConfigVersionSnapshot[] = [
  {
    id: 'snap-v1',
    version: 1,
    title: 'Certified Production Baseline Config',
    description: 'Initial institutional deployment with standard CBSE academic rules and billing pipelines.',
    createdBy: 'System Provisioner',
    createdAt: '2025-04-01 08:00 AM',
    snapshot: {},
    canRollback: false
  },
  {
    id: 'snap-v2',
    version: 2,
    title: 'Customization Studio & Module Expansion',
    description: 'Added custom fields engine, theme designer, multi-format certificates, and workflow state pipelines.',
    createdBy: 'Super Admin',
    createdAt: '2025-04-28 10:15 AM',
    snapshot: {},
    canRollback: true
  }
];
