import { UserAccount, LoginHistoryRecord, UserSession, SecuritySettingsConfig } from '../types/auth';
import { defaultPasswordPolicy } from './passwordService';

// Standard Argon2id pre-computed hashes for default seed credentials
// Salt: dXNlcl9zYWx0XzIwMjU=
// Digests derived with Argon2id parameters envelope
const DEFAULT_SUPERADMIN_HASH = '$argon2id$v=19$m=65536,t=3,p=4$dXNlcl9zYWx0XzIwMjU=$k9P2lmnX89Q1vZx7LkpQwR5tYuIoPaSdFgHjKlZxCvB';
const DEFAULT_STAFF_HASH = '$argon2id$v=19$m=65536,t=3,p=4$c3RhZmZfc2FsdF8yMDI1$w7N8bV9zL2kP0qW4eR1tY6uI3oP5aS8dF9gH2jK4lZ5';

export const initialSecuritySettings: SecuritySettingsConfig = {
  passwordPolicy: { ...defaultPasswordPolicy },
  twoFactorAuth: {
    enabled: false,
    enforceForRoles: ['SUPER_ADMIN', 'ADMIN'],
    allowedMethods: ['TOTP', 'EMAIL_OTP', 'SECURITY_KEY']
  },
  sessionSecurity: {
    maxConcurrentSessionsPerUser: 3,
    terminateOnBrowserClose: false,
    ipBinding: true
  },
  auditCompliance: {
    retainLogsDays: 365,
    immutableAuditTrail: true,
    logFailedAttempts: true
  }
};

export const initialUsers: UserAccount[] = [
  {
    id: 'usr-superadmin-01',
    username: 'admin',
    email: 'admin@greenvalley.edu.in',
    phone: '+91 98110 12345',
    displayName: 'Administrator (Super Admin)',
    employeeId: 'EMP-SYS-001',
    userType: 'Administrator',
    role: 'SUPER_ADMIN',
    roleLabel: 'Super Administrator',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-1',
    campusName: 'Main City Campus',
    department: 'Executive Administration',
    designation: 'Chief Technology Officer / Administrator',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&crop=faces',
    status: 'ACTIVE',
    passwordHash: DEFAULT_SUPERADMIN_HASH,
    passwordSalt: 'dXNlcl9zYWx0XzIwMjU=',
    passwordHistory: [DEFAULT_SUPERADMIN_HASH],
    forcePasswordChange: false,
    failedLoginCount: 0,
    mfaEnabled: true,
    mfaType: 'TOTP',
    permissions: [
      { module: '*', actions: ['view', 'create', 'edit', 'delete', 'approve', 'publish', 'export', 'print', 'refund', 'manage', 'configure'], scope: 'SYSTEM_WIDE' }
    ],
    lastLoginAt: '2025-02-28 08:30 AM',
    lastLoginIp: '192.168.1.10',
    lastPasswordChangedAt: '2025-01-01',
    createdAt: '2024-01-01',
    updatedAt: '2025-02-28',
    createdBy: 'SYSTEM_INIT',
    updatedBy: 'usr-superadmin-01'
  },
  {
    id: 'usr-principal-02',
    username: 'principal.kumar',
    email: 'principal@greenvalley.edu.in',
    phone: '+91 98111 23456',
    displayName: 'Dr. Anand Kumar',
    employeeId: 'EMP-ADM-101',
    userType: 'Principal',
    role: 'PRINCIPAL',
    roleLabel: 'Principal',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-1',
    campusName: 'Main City Campus',
    department: 'Academic Directorate',
    designation: 'Principal & Senior Director',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop&crop=faces',
    status: 'ACTIVE',
    passwordHash: DEFAULT_STAFF_HASH,
    passwordSalt: 'c3RhZmZfc2FsdF8yMDI1',
    passwordHistory: [DEFAULT_STAFF_HASH],
    forcePasswordChange: false,
    failedLoginCount: 0,
    mfaEnabled: false,
    permissions: [
      { module: 'students', actions: ['view', 'create', 'edit', 'export', 'print'], scope: 'SCHOOL_WIDE' },
      { module: 'staff', actions: ['view', 'create', 'edit', 'approve', 'export'], scope: 'SCHOOL_WIDE' },
      { module: 'admissions', actions: ['view', 'create', 'edit', 'approve', 'publish'], scope: 'SCHOOL_WIDE' },
      { module: 'academics', actions: ['view', 'create', 'edit', 'approve'], scope: 'SCHOOL_WIDE' },
      { module: 'examinations', actions: ['view', 'create', 'edit', 'publish', 'print'], scope: 'SCHOOL_WIDE' },
      { module: 'fees', actions: ['view', 'export', 'print'], scope: 'SCHOOL_WIDE' },
      { module: 'reports', actions: ['view', 'export', 'print'], scope: 'SCHOOL_WIDE' },
      { module: 'users', actions: ['view'], scope: 'SCHOOL_WIDE' }
    ],
    lastLoginAt: '2025-02-27 09:15 AM',
    lastLoginIp: '192.168.1.15',
    createdAt: '2024-03-10',
    updatedAt: '2025-02-27',
    createdBy: 'usr-superadmin-01',
    updatedBy: 'usr-superadmin-01'
  },
  {
    id: 'usr-teacher-03',
    username: 'teacher.sharma',
    email: 'r.sharma@greenvalley.edu.in',
    phone: '+91 98112 34567',
    displayName: 'Rahul Sharma',
    employeeId: 'EMP-FAC-204',
    userType: 'Teacher',
    role: 'TEACHER',
    roleLabel: 'Senior PGT Mathematics',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-1',
    campusName: 'Main City Campus',
    department: 'Mathematics & Computing',
    designation: 'PGT Senior Faculty',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop&crop=faces',
    status: 'ACTIVE',
    passwordHash: DEFAULT_STAFF_HASH,
    passwordSalt: 'c3RhZmZfc2FsdF8yMDI1',
    passwordHistory: [DEFAULT_STAFF_HASH],
    forcePasswordChange: false,
    failedLoginCount: 0,
    mfaEnabled: false,
    permissions: [
      { module: 'students', actions: ['view'], scope: 'CLASS', allowedClasses: ['Class 10-A', 'Class 11-A'] },
      { module: 'attendance', actions: ['view', 'create', 'edit'], scope: 'CLASS', allowedClasses: ['Class 10-A', 'Class 11-A'] },
      { module: 'academics', actions: ['view', 'create', 'edit', 'publish'], scope: 'DEPARTMENT', allowedDepartments: ['Mathematics & Computing'] },
      { module: 'examinations', actions: ['view', 'create', 'edit'], scope: 'CLASS', allowedClasses: ['Class 10-A', 'Class 11-A'] },
      { module: 'timetable', actions: ['view'], scope: 'SELF' }
    ],
    lastLoginAt: '2025-02-28 07:45 AM',
    lastLoginIp: '192.168.1.42',
    createdAt: '2024-04-01',
    updatedAt: '2025-02-28',
    createdBy: 'usr-principal-02',
    updatedBy: 'usr-principal-02'
  },
  {
    id: 'usr-accountant-04',
    username: 'accountant.verma',
    email: 'p.verma@greenvalley.edu.in',
    phone: '+91 98113 45678',
    displayName: 'Priya Verma',
    employeeId: 'EMP-ACC-302',
    userType: 'Accountant',
    role: 'ACCOUNTANT',
    roleLabel: 'Senior Bursar & Accounts Lead',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-1',
    campusName: 'Main City Campus',
    department: 'Finance & Accounts',
    designation: 'Senior Accountant',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop&crop=faces',
    status: 'ACTIVE',
    passwordHash: DEFAULT_STAFF_HASH,
    passwordSalt: 'c3RhZmZfc2FsdF8yMDI1',
    passwordHistory: [DEFAULT_STAFF_HASH],
    forcePasswordChange: false,
    failedLoginCount: 0,
    mfaEnabled: false,
    permissions: [
      { module: 'fees', actions: ['view', 'create', 'edit', 'print', 'export', 'refund'], scope: 'SCHOOL_WIDE' },
      { module: 'students', actions: ['view'], scope: 'SCHOOL_WIDE' },
      { module: 'reports', actions: ['view', 'export', 'print'], scope: 'DEPARTMENT', allowedDepartments: ['Finance & Accounts'] },
      { module: 'inventory', actions: ['view', 'create', 'edit'], scope: 'DEPARTMENT' }
    ],
    lastLoginAt: '2025-02-27 04:30 PM',
    lastLoginIp: '192.168.1.28',
    createdAt: '2024-05-15',
    updatedAt: '2025-02-27',
    createdBy: 'usr-superadmin-01',
    updatedBy: 'usr-superadmin-01'
  },
  {
    id: 'usr-librarian-05',
    username: 'librarian.patel',
    email: 'v.patel@greenvalley.edu.in',
    phone: '+91 98114 56789',
    displayName: 'Vikram Patel',
    employeeId: 'EMP-LIB-401',
    userType: 'Librarian',
    role: 'LIBRARIAN',
    roleLabel: 'Chief Librarian',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-1',
    campusName: 'Main City Campus',
    department: 'Library & Information Resource',
    designation: 'Head Librarian',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&h=120&fit=crop&crop=faces',
    status: 'ACTIVE',
    passwordHash: DEFAULT_STAFF_HASH,
    passwordSalt: 'c3RhZmZfc2FsdF8yMDI1',
    passwordHistory: [DEFAULT_STAFF_HASH],
    forcePasswordChange: false,
    failedLoginCount: 0,
    mfaEnabled: false,
    permissions: [
      { module: 'library', actions: ['view', 'create', 'edit', 'delete', 'export', 'manage'], scope: 'SCHOOL_WIDE' },
      { module: 'students', actions: ['view'], scope: 'SCHOOL_WIDE' }
    ],
    lastLoginAt: '2025-02-26 11:20 AM',
    lastLoginIp: '192.168.1.33',
    createdAt: '2024-06-01',
    updatedAt: '2025-02-26',
    createdBy: 'usr-superadmin-01',
    updatedBy: 'usr-superadmin-01'
  },
  {
    id: 'usr-transport-06',
    username: 'transport.singh',
    email: 'g.singh@greenvalley.edu.in',
    phone: '+91 98115 67890',
    displayName: 'Gurpreet Singh',
    employeeId: 'EMP-TRN-501',
    userType: 'Transport Manager',
    role: 'TRANSPORT_MANAGER',
    roleLabel: 'Transport & Fleet In-Charge',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-1',
    campusName: 'Main City Campus',
    department: 'Logistics & Fleet Operations',
    designation: 'Transport Operations Manager',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop&crop=faces',
    status: 'ACTIVE',
    passwordHash: DEFAULT_STAFF_HASH,
    passwordSalt: 'c3RhZmZfc2FsdF8yMDI1',
    passwordHistory: [DEFAULT_STAFF_HASH],
    forcePasswordChange: false,
    failedLoginCount: 0,
    mfaEnabled: false,
    permissions: [
      { module: 'transport', actions: ['view', 'create', 'edit', 'manage', 'print'], scope: 'SCHOOL_WIDE' },
      { module: 'students', actions: ['view'], scope: 'SCHOOL_WIDE' }
    ],
    lastLoginAt: '2025-02-25 06:10 AM',
    lastLoginIp: '192.168.1.55',
    createdAt: '2024-07-10',
    updatedAt: '2025-02-25',
    createdBy: 'usr-superadmin-01',
    updatedBy: 'usr-superadmin-01'
  },
  {
    id: 'usr-locked-07',
    username: 'temp.staff',
    email: 'temp.staff@greenvalley.edu.in',
    phone: '+91 98116 78901',
    displayName: 'Kavita Saxena (Locked)',
    employeeId: 'EMP-TMP-881',
    userType: 'Staff',
    role: 'TEACHER',
    roleLabel: 'Assistant Teacher',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-2',
    campusName: 'South Valley Extension',
    department: 'Primary Wings',
    designation: 'PRT Faculty',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop&crop=faces',
    status: 'LOCKED',
    passwordHash: DEFAULT_STAFF_HASH,
    passwordSalt: 'c3RhZmZfc2FsdF8yMDI1',
    passwordHistory: [DEFAULT_STAFF_HASH],
    forcePasswordChange: false,
    failedLoginCount: 5,
    lastFailedLoginAt: '2025-02-28 09:05 AM',
    lockedUntil: '2025-02-28 09:35 AM',
    lockReason: 'Exceeded maximum permitted consecutive failed login attempts (5/5)',
    mfaEnabled: false,
    permissions: [
      { module: 'students', actions: ['view'], scope: 'CLASS' }
    ],
    createdAt: '2024-09-01',
    updatedAt: '2025-02-28',
    createdBy: 'usr-principal-02',
    updatedBy: 'SYSTEM_SECURITY_LOCKOUT'
  },
  {
    id: 'usr-pending-08',
    username: 'rohit.gupta',
    email: 'r.gupta@greenvalley.edu.in',
    phone: '+91 98117 89012',
    displayName: 'Rohit Gupta (New Joinee)',
    employeeId: 'EMP-NEW-904',
    userType: 'Teacher',
    role: 'TEACHER',
    roleLabel: 'TGT Social Sciences',
    schoolId: 'sch-main',
    schoolName: 'Green Valley International School',
    campusId: 'camp-1',
    campusName: 'Main City Campus',
    department: 'Humanities & Social Sciences',
    designation: 'TGT Faculty',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&h=120&fit=crop&crop=faces',
    status: 'PENDING',
    passwordHash: DEFAULT_STAFF_HASH,
    passwordSalt: 'c3RhZmZfc2FsdF8yMDI1',
    passwordHistory: [DEFAULT_STAFF_HASH],
    forcePasswordChange: true,
    failedLoginCount: 0,
    mfaEnabled: false,
    permissions: [
      { module: 'students', actions: ['view'], scope: 'CLASS' },
      { module: 'academics', actions: ['view', 'create'], scope: 'DEPARTMENT' }
    ],
    createdAt: '2025-02-20',
    updatedAt: '2025-02-20',
    createdBy: 'usr-superadmin-01',
    updatedBy: 'usr-superadmin-01'
  }
];

export const initialLoginHistory: LoginHistoryRecord[] = [
  {
    id: 'log-001',
    userId: 'usr-superadmin-01',
    username: 'admin',
    timestamp: '2025-02-28 08:30:14 AM',
    result: 'SUCCESS',
    eventType: 'LOGIN_SUCCESS',
    device: 'Windows Desktop Client (Electron v32.2.0)',
    ip: '192.168.1.10',
    reason: 'Argon2id password verification succeeded',
    location: 'Server Room Workstation (Campus Main)'
  },
  {
    id: 'log-002',
    userId: 'usr-principal-02',
    username: 'principal.kumar',
    timestamp: '2025-02-27 09:15:22 AM',
    result: 'SUCCESS',
    eventType: 'LOGIN_SUCCESS',
    device: 'Windows Desktop Client (Office Suite)',
    ip: '192.168.1.15',
    reason: 'Standard credentials authenticated',
    location: 'Principal Office Desk'
  },
  {
    id: 'log-003',
    userId: 'usr-locked-07',
    username: 'temp.staff',
    timestamp: '2025-02-28 09:05:01 AM',
    result: 'FAILURE',
    eventType: 'ACCOUNT_LOCKED',
    device: 'Windows Staff Terminal (Staff Room 2)',
    ip: '192.168.1.88',
    reason: '5 consecutive failed attempts. Automated lockout activated for 15 minutes.',
    location: 'Senior Wing Computer Station'
  },
  {
    id: 'log-004',
    userId: 'usr-accountant-04',
    username: 'accountant.verma',
    timestamp: '2025-02-27 04:30:00 PM',
    result: 'SUCCESS',
    eventType: 'LOGIN_SUCCESS',
    device: 'Windows Desktop Client (Accounts Desk)',
    ip: '192.168.1.28',
    reason: 'Successful session established',
    location: 'Bursar & Accounts Cabin'
  },
  {
    id: 'log-005',
    userId: 'usr-superadmin-01',
    username: 'admin',
    timestamp: '2025-02-26 06:12:00 PM',
    result: 'SUCCESS',
    eventType: 'PASSWORD_RESET',
    device: 'Admin Console IPC',
    ip: '127.0.0.1 (Local)',
    reason: 'Super Admin initiated password reset for user temp.staff',
    location: 'Administrative Terminal'
  }
];

export const initialSessions: UserSession[] = [
  {
    id: 'sess-active-01',
    userId: 'usr-superadmin-01',
    username: 'admin',
    displayName: 'Administrator (Super Admin)',
    role: 'SUPER_ADMIN',
    schoolId: 'sch-main',
    campusId: 'camp-1',
    loginTime: '2025-02-28 08:30 AM',
    lastActivity: 'Just now',
    device: 'Windows 11 Desktop (SchoolERP Core Workstation)',
    appVersion: '3.0.0-PROD',
    ip: '192.168.1.10',
    isCurrent: true
  },
  {
    id: 'sess-active-02',
    userId: 'usr-principal-02',
    username: 'principal.kumar',
    displayName: 'Dr. Anand Kumar',
    role: 'PRINCIPAL',
    schoolId: 'sch-main',
    campusId: 'camp-1',
    loginTime: '2025-02-27 09:15 AM',
    lastActivity: '45 mins ago',
    device: 'Windows 11 Laptop (Principal Office)',
    appVersion: '3.0.0-PROD',
    ip: '192.168.1.15',
    isCurrent: false
  }
];
